apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
  namespace: backend
  labels:
    app: queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      name: queue
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: arjansubedi/queueservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
              protocol: TCP
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
      restartPolicy: Always
      