apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: backend
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6739
  type: ClusterIP
  