apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: backend
spec:
  project: default
  source:
    repoURL: 'https://github.com/itisaarjan/TaskQueueHandler'
    targetRevision: main
    path: infra/k8s/argoCD/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:   
      prune: true
      selfHeal: true
