apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-worker
  namespace: backend
  labels:
    app: image-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-worker
  template:
    metadata:
      name: image-worker
      labels:
        app: image-worker
    spec:
      containers:
        - name: image-worker
          image: arjansubedi/imageworker:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
              protocol: TCP
      restartPolicy: Always
      