resources:
  - resources/backend-namespace.yaml
  - resources/queue.yaml
  - resources/queue-service.yaml
  - resources/task-queue-service.yaml
  - resources/task-db-service.yaml
  - resources/redis.yaml
  - resources/redis-service.yaml
  - resources/redis-pvc.yaml
  - resources/postgress.yaml
  - resources/postgres-service.yaml
  - resources/postgress-pvc.yaml
  - resources/imageworker.yaml
  - resources/emailworker.yaml
