apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-queue
  namespace: backend
  labels:
    app: task-queue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-queue
  template:
    metadata:
      labels:
        app: task-queue
    spec:
      containers:
        - name: task-queue
          image: arjansubedi/task-queue:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATA_REDIS_HOST
              value: "redis-service"
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"