apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: email-service-monitor
  namespace: backend
  labels:
    app: email-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: email-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - backend

