apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: image-worker-monitor
  namespace: backend
  labels:
    app: image-worker
    release: prometheus
spec:
  selector:
    matchLabels:
      app: image-worker
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - backend

