apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/itisaarjan/TaskQueueHandler'
    targetRevision: main
    path: infra/k8s/argoCD/platform/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:   
      prune: true
      selfHeal: true
