apiVersion: v1
kind: Service
metadata:
  name: task-queue-service
spec:
  selector:
    app: task-queue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
