grafana:
  enabled: true
  adminPassword: admin
  service:
    type: NodePort
  ingress:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true

sidecar:
  grafana_alert: true