apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: backend
  labels:
    app: email-service
spec:
  selector:
    app: email-service
  ports:
    - name: http
      protocol: TCP
      port: 8004
      targetPort: 8004
  type: ClusterIP

