apiVersion: v1
kind: Service
metadata:
  name: queue-service
  namespace: backend
spec:
  selector:
    app: queue
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
  