name: Build and Push Docker Images

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'service/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'service/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        service: [task-queue, QueueService, ImageWorker, EmailService, TaskDBService]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set lowercase image name
        id: vars
        run: echo "imagename=$(echo '${{ matrix.service }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./service/${{ matrix.service }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: arjansubedi/${{ env.imagename }}:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=arjansubedi/${{ env.imagename }}:buildcache
          cache-to: type=registry,ref=arjansubedi/${{ env.imagename }}:buildcache,mode=max

      - name: Image digest
        run: echo "Image pushed with digest ${{ steps.build-push.outputs.digest }}"

  summary:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Build summary
        run: |
          echo "## Docker Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Build completed for all services!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Services Built:" >> $GITHUB_STEP_SUMMARY
          echo "- EmailService (Port 8004)" >> $GITHUB_STEP_SUMMARY
          echo "- QueueService (Port 8001)" >> $GITHUB_STEP_SUMMARY
          echo "- ImageWorker (Port 8003)" >> $GITHUB_STEP_SUMMARY
          echo "- TaskQueue (Port 8000)" >> $GITHUB_STEP_SUMMARY
          echo "- TaskDBService (Port 8002)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Docker Hub:" >> $GITHUB_STEP_SUMMARY
          echo "Images available at: https://hub.docker.com/u/arjansubedi" >> $GITHUB_STEP_SUMMARY
