name: Build and Push Frontend Image

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-build.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: arjansubedi/taskqueue-frontend:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=arjansubedi/taskqueue-frontend:buildcache
          cache-to: type=registry,ref=arjansubedi/taskqueue-frontend:buildcache,mode=max

      - name: Image digest
        run: echo "Image pushed with digest ${{ steps.build-push.outputs.digest }}"

      - name: Build summary
        run: |
          echo "## Frontend Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Frontend image built and pushed successfully!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Image Details:" >> $GITHUB_STEP_SUMMARY
          echo "- Repository: arjansubedi/taskqueue-frontend" >> $GITHUB_STEP_SUMMARY
          echo "- Tag: latest" >> $GITHUB_STEP_SUMMARY
          echo "- Docker Hub: https://hub.docker.com/r/arjansubedi/taskqueue-frontend" >> $GITHUB_STEP_SUMMARY

